### ISSUE TITLE
sometimes the "success" message fails to appear

### ISSUE THREAD

**Issue by jordansread** [USGS-R/ds-pipelines-1-course#12]
no changes to this section, but the message we expect for success doesn't show up _sometimes_. Perhaps as bad as 50%?

![image](https://user-images.githubusercontent.com/2349007/81185789-a3c99a00-8f77-11ea-970f-ac5a97371899.png)

```yaml
    link: '{{ store.install_activity_url }}'
    event: issue_comment.created
    actions:
      - type: gate
        left: USGS Support Package
        operator: test
        right: '%payload.comment.body%'
        else:
          - type: respond
            with: 01a-install-fail.md
      - type: respond
        with: 01b-install-success.md
      - type: closeIssue
      - type: createIssue
        title: Structure your code predictably
        body: 10-structure.md
        store:
          structure_issue_url: '{{ result.data.html_url }}'
          structure_issue_id: '{{ payload.issue.number }}'
```

let's keep our eye on this...
