### ISSUE TITLE
Set up pipelines I w/o using target_name, or explain it better

### ISSUE THREAD

**Issue by jordansread** [USGS-R/ds-pipelines-1-course#58]
`target_name` is a neat and useful special arg, but isn't explained or revealed with an activity. It is easy to not understand what it is doing and what it is used for. 

I thought that a small revision to this course would be to avoid it completely, then reveal it in `tips-and-tricks` (course 2) with part of an exercise. 

In pipelines I, I think the first place is comes in is here:

The simplest version of a remakefile (adapted from the remake repo) might look something like this:
```yaml
sources:
  - code.R

targets:
  all:
    depends: figure_1.png

  model_RMSEs.csv:
    command: download_data(target_name)

  processed:
    command: process_data("model_RMSEs.csv")

  figure_1.png:
    command: myplot(target_name, processed)
```

**Comment by jordansread** [comment]
Using 
```yaml
sources:
  - code.R

targets:
  all:
    depends: figure_1.png

  model_RMSEs.csv:
    command: download_data(out_filepath = "model_RMSEs.csv")

  plot_data:
    command: process_data(in_filepath = "model_RMSEs.csv")

  figure_1.png:
    command: myplot(out_filepath = "figure_1.png", data = plot_data)

```
instead with 

![image](https://user-images.githubusercontent.com/2349007/82728127-16df4a00-9cb4-11ea-927a-a68a1d5dea00.png)
